services:
  mysql:
    image: mysql:9.3.0
    container_name: quran_interview_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quran
      MYSQL_USER: nextjs
      MYSQL_PASSWORD: nextjs
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - quran_mysql_data:/var/lib/mysql
      - ./create_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      start_period: 0s
      timeout: 5s

volumes:
  quran_mysql_data:
